# Install Paru from source
- name: Install Paru dependencies
  become: yes
  pacman:
    name: "{{ item }}"
    state: present
  with_items:
    - base-devel

- name: Clone Paru repository
  git:
    repo: https://aur.archlinux.org/paru.git
    dest: "{{ lookup('env', 'HOME') }}/software/paru"

- name: Build and install Paru
  shell: |
    cd {{ lookup('env', 'HOME') }}/software/paru
    makepkg -si
  args:
    chdir: "{{ lookup('env', 'HOME') }}/software/paru"
  become: yes
  become_user: "{{ lookup('env', 'USER') }}"
